language: python
python:
    - "3.4"
    - "3.5"
services:
    - redis
install:
    - pip install -r requirements/base.txt
    - pip install -r requirements/test.txt
    - pip install coveralls
script:
    - cd election_reminders
    - coverage run --source=. --omit="staff/management/commands/*" manage.py test
after_success:
    - coveralls
