language: python
python:
    - "3.4"
    - "3.5"
services:
    - redis
install:
    - pip install -r requirements/base.txt
    - pip install -r requirements/test.txt
script:
    - cd election_reminders
    - python manage.py test
