# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(help_text='User friendly name., eg Virginia Primary Election', max_length=255),
        ),
        migrations.AlterField(
            model_name='election',
            name='state',
            field=models.CharField(blank=True, help_text='2 letter representation of the state. Blank if national election.', max_length=2),
        ),
    ]
