# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateTimeField(db_index=True, help_text='When this election will be held.'),
        ),
    ]
