# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 02:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsubscribed', models.BooleanField(default=False)),
                ('street_address', models.CharField(help_text='Ex: 123 Brown St', max_length=127)),
                ('city', models.CharField(help_text='Ex: New York City', max_length=64)),
                ('state', models.CharField(help_text='2 letter upper case state code. Ex: VA', max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +99999999.', regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
