# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 05:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +99999999.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
