# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media_type',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_before_election',
            field=models.DurationField(help_text='Ex: 2 days to send a reminder 2 days before all elections.Format is "days hours:min:secs". Ex: "1 02:00:00" for one day, 2 hours before.'),
        ),
    ]
