# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_auto_20160127_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
